services:
  web:
    container_name: factshield_web
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: factshield_redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  celery_worker:
    container_name: factshield_celery_worker
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web 