version: '3.9'

services:
  web:
    container_name: factshield_web
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: factshield_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
